PRAGMA foreign_keys=OFF;
BEGIN TRANSACTION;
CREATE TABLE groups(id INTEGER PRIMARY KEY AUTOINCREMENT, name varchar(64), info varchar(128), pos int);
INSERT INTO "groups" VALUES(1,'','',1);
INSERT INTO "groups" VALUES(2,'Helpers','Помощники',3);
INSERT INTO "groups" VALUES(3,'Interface','Интерфейс',2);
CREATE TABLE elements(id INTEGER PRIMARY KEY AUTOINCREMENT, name varchar(64), info varchar(64), tab int, pos int, hash varchar(32));
INSERT INTO "elements" VALUES(1,'*Helpers_Схема','Схема',2,1,NULL);
INSERT INTO "elements" VALUES(2,'LineBreak','Разрыв линии',2,2,NULL);
INSERT INTO "elements" VALUES(3,'LineBreakEx','Разрыв линии',2,3,NULL);
INSERT INTO "elements" VALUES(4,'GetDataEx','Продвинутый Доступ к данным',2,5,NULL);
INSERT INTO "elements" VALUES(5,'Check','Флажок',2,6,NULL);
INSERT INTO "elements" VALUES(6,'*Helpers_Дизайн','Дизайн',2,7,NULL);
INSERT INTO "elements" VALUES(7,'InfoTip','Вывод подсказки в окне редактора',2,8,NULL);
INSERT INTO "elements" VALUES(8,'LinkTip','Гиперссылка в редакторе',2,9,NULL);
INSERT INTO "elements" VALUES(9,'Shape','Фигура',2,10,NULL);
INSERT INTO "elements" VALUES(10,'PictureTip','Отображение картинки в редакторе программы',2,11,NULL);
INSERT INTO "elements" VALUES(11,'PointHint','Сноска',2,12,NULL);
INSERT INTO "elements" VALUES(12,'ImageMulti','Отображение схем в редакторе',2,13,NULL);
INSERT INTO "elements" VALUES(13,'ViewSHA','Отображение схем в редакторе',2,14,NULL);
INSERT INTO "elements" VALUES(14,'*Helpers_Среда','Среда',2,15,NULL);
INSERT INTO "elements" VALUES(15,'SDKBtn','Кнопка на рабочем столе',2,16,NULL);
INSERT INTO "elements" VALUES(16,'AccessFTP','Доступ к FTP',2,17,NULL);
INSERT INTO "elements" VALUES(17,'ScriptEvents','События скрипта',2,18,NULL);
INSERT INTO "elements" VALUES(18,'BugReport','Сбор данных о схеме и её окружении',2,19,NULL);
INSERT INTO "elements" VALUES(19,'Toast','',3,1,NULL);
INSERT INTO "elements" VALUES(20,'DoData','Заносит данные в поток',3,2,NULL);
INSERT INTO "elements" VALUES(21,'MainActivity','Главная форма приложения',1,1,NULL);
CREATE TABLE files(id INTEGER PRIMARY KEY AUTOINCREMENT, name varchar(128), count int);
CREATE TABLE files_link(file_id int, el_id int);
DELETE FROM sqlite_sequence;
INSERT INTO "sqlite_sequence" VALUES('groups',3);
INSERT INTO "sqlite_sequence" VALUES('elements',21);
COMMIT;
